### ISSUE TITLE
Can not update module after go.mod introduction

### ISSUE THREAD

**Issue by aivarasbaranauskas** [xitongsys/parquet-go-source#15]
When running `go get -u github.com/xitongsys/parquet-go-source` I am getting this error:
```
go: github.com/xitongsys/parquet-go-source upgrade => v0.0.0-20200502003254-3a4231c65b99
go get: github.com/xitongsys/parquet-go-source@v0.0.0-20200502003254-3a4231c65b99: parsing go.mod:
	module declares its path as: parquet-go-source
	        but was required as: github.com/xitongsys/parquet-go-source
```
I suspect this is caused by go.mod having module name as 'parquet-go-source' and nod as 'github.com/xitongsys/parquet-go-source'.

**Comment by aivarasbaranauskas** [comment]
Just realised there is already a PR for this: #14

**Comment by quantumchaos451** [comment]
+1

**Comment by xitongsys** [comment]
hi, 
sorry for late response and I missed this. 
Already merged, please recheck. Thanks.

**Comment by aivarasbaranauskas** [comment]
Works now. Thank you!
