### ISSUE TITLE
GCS Writer example doesn't work

### ISSUE THREAD

**Issue by simplylizz** [xitongsys/parquet-go-source#17]
I'm trying to use code from the example.
1. It just hangs with parallelism set to 4 (see https://github.com/xitongsys/parquet-go/issues/256).
2. With parallelism set to 1:
```
2020/06/04 11:12:06 WriteStop error interface conversion: interface {} is []uint8, not string
2020/06/04 11:12:06 Write Finished
```
And it creates 4-bytes file on GCS which contains only `PAR1` header.

There is some issue with writing strings (i.e. particularly `student_name`) field.

So with commented recovery inside writer the error looks like this:
```
panic: interface conversion: interface {} is []uint8, not string

goroutine 44 [running]:
github.com/xitongsys/parquet-go/common.Cmp(0x1674820, 0xc00000e6a0, 0x1674820, 0xc00000e6a0, 0xc000604340, 0xc000604338, 0x203000)
	/Users/cw1993/go/pkg/mod/github.com/xitongsys/parquet-go@v1.5.2/common/common.go:453 +0xc6b
github.com/xitongsys/parquet-go/common.Max(...)
	/Users/cw1993/go/pkg/mod/github.com/xitongsys/parquet-go@v1.5.2/common/common.go:508
github.com/xitongsys/parquet-go/layout.TableToDictDataPages(0xc0002249f0, 0xc00017c400, 0x2000002000, 0x1, 0xc000120a48, 0xc00017a200, 0xc000010108, 0x0)
	/Users/cw1993/go/pkg/mod/github.com/xitongsys/parquet-go@v1.5.2/layout/dictpage.go:95 +0x6bd
github.com/xitongsys/parquet-go/writer.(*ParquetWriter).flushObjs.func1(0xc000604670, 0xc00013a280, 0xc000604660, 0xc00000e7a0, 0x4, 0x4, 0xc00011b120, 0xf, 0x14, 0x3)
	/Users/cw1993/go/pkg/mod/github.com/xitongsys/parquet-go@v1.5.2/writer/writer.go:239 +0x2de
created by github.com/xitongsys/parquet-go/writer.(*ParquetWriter).flushObjs
	/Users/cw1993/go/pkg/mod/github.com/xitongsys/parquet-go@v1.5.2/writer/writer.go:208 +0x2ab
```

**Comment by xitongsys** [comment]
hi, @simplylizz 
Does the same code work in local? 
I know there are some issues in the GCS. But I can't debug it. You can found some details in #220

**Comment by simplylizz** [comment]
> Does the same code work in local?

Nope, exactly the same behaviour.

**Comment by xitongsys** [comment]
hi, @simplylizz 
could you provide you code ?

**Comment by simplylizz** [comment]
The error happens here:
https://github.com/xitongsys/parquet-go/blob/v1.5.2/common/common.go#L453

Because `ai = "Student Name_0"` while `bi = []uint8{...}`, so basically content of bi is ascii codes of `"Student Name"`.

In the master you have refactored code, but the issue still happens the `LessThan` function.

See #18.

**Comment by xitongsys** [comment]
ok, thanks. Merged.
