### ISSUE TITLE
No Go files

### ISSUE THREAD

**Issue by alexgoloshumov** [xitongsys/parquet-go-source#23]
C:\Go_test\src>go get github.com\xitongsys\parquet-go-source
package github.com/xitongsys/parquet-go-source: no Go files in C:\Go_test\src\github.com\xitongsys\parquet-go-source

C:\Go_test\src>go version
go version go1.15 windows/amd64

what i doing wrong ?

**Comment by briansorahan** [comment]
@alexgoloshumov try
```
go get github.com\xitongsys\parquet-go-source\...
```

**Comment by alexgoloshumov** [comment]
src\github.com\xitongsys\parquet-go\parquet\parquet.go:631:37: not enough arguments in call to iprot.ReadStructBegin
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:637:57: not enough arguments in call to iprot.ReadFieldBegin
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:649:29: not enough arguments in call to iprot.Skip
        have (thrift.TType)
        want (context.Context, thrift.TType)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:708:33: not enough arguments in call to iprot.ReadFieldEnd
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:712:32: not enough arguments in call to iprot.ReadStructEnd
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:719:32: not enough arguments in call to iprot.ReadBinary
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:728:32: not enough arguments in call to iprot.ReadBinary
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:737:29: not enough arguments in call to iprot.ReadI64
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:746:29: not enough arguments in call to iprot.ReadI64
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:755:32: not enough arguments in call to iprot.ReadBinary
        have ()
        want (context.Context)
src\github.com\xitongsys\parquet-go\parquet\parquet.go:755:32: too many errors

**Comment by kevinisbest** [comment]
Hi @alexgoloshumov, seems the same problem [here](https://github.com/xitongsys/parquet-go/issues/292#issue-643168217).
Maybe use the specific version of thrift library can solve the problem.
