### ISSUE TITLE
Allow to modify PutObjectInput with s3v2 parquet-go-source

### ISSUE THREAD

**Issue by Nitjsefni7** [xitongsys/parquet-go-source#45]
While using `func NewS3FileWriterWithClient()` we are able to supply uploaderOptions, however we can't modify PutObjectInput
https://github.com/xitongsys/parquet-go-source/blob/b4f792c43cd0b2477327d56a74970efca07af04e/s3v2/s3.go#L290-L294

Which prevents us for example from defining Metadata for uploaded file.
Would be great to allow supply additional information with PutObjectInput while creating new writer.

Similar issue, but with s3 source: #20

**Comment by xrn** [comment]
@xitongsys can you take a look on this please?
