### ISSUE TITLE
Need help in reading parquet file in chunks from GCS

### ISSUE THREAD

**Issue by saiteja2021** [xitongsys/parquet-go-source#73]
using multi Reader to read the file in chunks 

```
multiReader := io.MultiReader(mReader)

	for {
		buf := make([]byte, 1024)
		n, err := multiReader.Read(buf)
		if err != nil {
			if err == io.EOF {
				break
			}
			return nil, err
		}

		pr, err := pr.NewParquetReader(buf, new(ProcLog), 4)
		if err != nil {
		
			return nil, err
		}
		fmt.Println(string(buf[:n]))
	}
```

now wants to convert  only one chunk to string from parquet format. 
like converting  parquet  data in buffer to string or a struct 
Any help is highly appreciated .

**Comment by sbyrdsellGIT** [comment]
Hi saiteja2021,

I'm new to golang but here is my approach:

```
func makeRange(min, max int) []int {
	a := make([]int, max-min+1)
	for i := range a {
		a[i] = min + i
	}
	return a
}

func chunkSlice(slice []int, chunkSize int) [][]int {
	var chunks [][]int
	for i := 0; i < len(slice); i += chunkSize {
		end := i + chunkSize
		if end > len(slice) {
			end = len(slice)
		}

		chunks = append(chunks, slice[i:end])
	}

	return chunks
}
```

Set your chunkSize
`chunkSize := 30000`

Read in your local parquet
```
parquetFile := "../data/c000.snappy.parquet"

fr, err := local.NewLocalFileReader(parquetFile)
if err != nil {
      log.Println("Can't open file: ", parquetFile)
      os.Exit(1)
}
defer fr.Close()
```

Call  NewParquetReader using the chunkSize as the  NP int64 //parallel number
Note:
I struggle with this parameter, when I set it too low like 4 I get an indexing error....
`Read error Error: runtime error: index out of range [4] with length 4`
My parquet file is constructed of a lot of embedded arrays of mapped struct of all types.
If someone can help with this part I would appreciate it.


```
pr, err := reader.NewParquetReader(fr, nil, int64(chunkSize))
if err != nil {
        log.Println("Can't create parquet reader", err)
	return
}
defer pr.ReadStop()
```

Get the number of rows from the reader
```
num := int(pr.GetNumRows())
rang := makeRange(1, num)
xloop := chunkSlice(rang, chunkSize)

for i := 0; i < len(xloop); i++ {
		
		fmt.Println(fmt.Sprintf("chunkSize:-> %v ChunkSlice: -> %v of %v", chunkSize, i+1, l))
		stus := make([]sayari.Entity, chunkSize) //read chunkSize rows

		if err = pr.Read(&stus); err != nil {
			logger.Error(fmt.Sprintf("Read error %s", err))
		}

		x := (chunkSize - len(stus))
		logger.Info(fmt.Sprintf("Total number records lost: %v out of %v\n\n", x, len(stus)))
}
```

Hope this helps....

**Comment by saiteja2021** [comment]
i have found a way to do it

**Comment by saiteja2021** [comment]
https://github.com/segmentio/parquet-go
this pkg can stream data into gcs row by row 
like  below
genWriter = pq.NewGenericWriter[any](writer, schema, pq.Compression(&pq.Snappy))
_, err := genWriter.Write([]any{x})

**Comment by sbyrdsellGIT** [comment]
Thanks
